// Get the current tab and display domain information
async function getCurrentTab() {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  return tab;
}

function extractDomain(url) {
  try {
    const urlObj = new URL(url);
    return urlObj.hostname;
  } catch (error) {
    return null;
  }
}

async function getCookiesForDomain(domain) {
  try {
    const cookies = await chrome.cookies.getAll({ domain: domain });
    
    // Also try to get cookies for subdomains
    const domainParts = domain.split('.');
    if (domainParts.length > 2) {
      // Try base domain (e.g., example.com from www.example.com)
      const baseDomain = domainParts.slice(-2).join('.');
      const baseCookies = await chrome.cookies.getAll({ domain: baseDomain });
      
      // Merge and deduplicate
      const allCookies = [...cookies];
      baseCookies.forEach(cookie => {
        if (!allCookies.find(c => c.name === cookie.name && c.domain === cookie.domain)) {
          allCookies.push(cookie);
        }
      });
      
      return allCookies;
    }
    
    return cookies;
  } catch (error) {
    console.error('Error getting cookies:', error);
    return [];
  }
}

function formatCookiesAsNetscape(cookies) {
  // Netscape HTTP Cookie File format (used by curl, wget, yt-dlp, etc.)
  let text = '# Netscape HTTP Cookie File\n';
  text += '# https://curl.se/docs/http-cookies.html\n';
  text += '# This file was generated by Cookie Exporter extension\n';
  
  if (cookies.length === 0) {
    return text;
  }
  
  cookies.forEach(cookie => {
    // Format: domain flag domain path secure expiration name value
    // domain: The domain that can read the cookie
    // flag: TRUE if domain begins with a dot (subdomain), FALSE otherwise
    // path: The path within the domain that the cookie is valid for
    // secure: TRUE if connection must be secure (HTTPS), FALSE otherwise
    // expiration: Unix timestamp of expiration (or 0 for session cookies)
    // name: The cookie name
    // value: The cookie value
    
    const domain = cookie.domain.startsWith('.') ? cookie.domain : cookie.domain;
    const flag = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = cookie.path;
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiration = cookie.expirationDate ? Math.floor(cookie.expirationDate) : '0';
    const name = cookie.name;
    const value = cookie.value;
    
    text += `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
  });
  
  return text;
}

async function exportCookies() {
  const exportBtn = document.getElementById('exportBtn');
  const statusDiv = document.getElementById('status');
  
  // If button says "Close", just close the popup
  if (exportBtn.textContent === 'Close') {
    window.close();
    return;
  }
  
  // Security warning
  const userConfirmed = confirm(
    '⚠️ SECURITY WARNING\n\n' +
    'Exported cookies contain sensitive authentication data that can be used to access your accounts.\n\n' +
    '• Cookie data is stored UNENCRYPTED in plain text\n' +
    '• Store the exported file securely\n' +
    '• Do not share it with untrusted parties\n' +
    '• Delete the file when no longer needed\n\n' +
    'Do you want to continue?'
  );
  
  if (!userConfirmed) {
    return;
  }
  
  try {
    exportBtn.disabled = true;
    statusDiv.className = 'status';
    statusDiv.textContent = 'Exporting cookies...';
    statusDiv.style.display = 'block';
    
    const tab = await getCurrentTab();
    const domain = extractDomain(tab.url);
    
    if (!domain) {
      throw new Error('Unable to extract domain from current tab');
    }
    
    const cookies = await getCookiesForDomain(domain);
    const cookieText = formatCookiesAsNetscape(cookies);
    
    // Create a blob and download it
    const blob = new Blob([cookieText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    // Clean domain name for filename (remove special characters)
    const cleanDomain = domain.replace(/[^a-zA-Z0-9.-]/g, '_');
    const filename = `cookies_${cleanDomain}.txt`;
    
    await chrome.downloads.download({
      url: url,
      filename: filename,
      saveAs: true
    });
    
    // Clean up the blob URL after a short delay
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    
    statusDiv.className = 'status success';
    statusDiv.textContent = `✓ Export complete! ${cookies.length} cookie(s) saved to ${filename}`;
    
    // Change button to close button
    exportBtn.textContent = 'Close';
    exportBtn.disabled = false;
    
  } catch (error) {
    console.error('Export error:', error);
    statusDiv.className = 'status error';
    statusDiv.textContent = `✗ Error: ${error.message}`;
    exportBtn.disabled = false;
  }
}

// Initialize popup
async function init() {
  const domainEl = document.getElementById('domain');
  const cookieCountEl = document.getElementById('cookieCount');
  const exportBtn = document.getElementById('exportBtn');
  
  try {
    const tab = await getCurrentTab();
    const domain = extractDomain(tab.url);
    
    if (!domain) {
      domainEl.textContent = 'Invalid URL';
      exportBtn.disabled = true;
      return;
    }
    
    domainEl.textContent = domain;
    
    // Get cookie count
    const cookies = await getCookiesForDomain(domain);
    cookieCountEl.textContent = `${cookies.length} cookie(s) found`;
    
    if (cookies.length === 0) {
      cookieCountEl.style.color = '#999';
    }
    
  } catch (error) {
    console.error('Init error:', error);
    domainEl.textContent = 'Error loading domain';
    exportBtn.disabled = true;
  }
}

// Event listeners
document.getElementById('exportBtn').addEventListener('click', exportCookies);

// Initialize when popup opens
init();
